language: ruby
rvm:
- 2.1.2
gemfile: Gemfile
deploy:
  provider: heroku
  api_key:
    secure: TQr/tEH7z2n9wE5FDlu7CAu3rg5x69030lnH+EUCXs0BhmoMs5w7N0kz2SUX4MmXnYmTQreoaWKvoQ5nCSSJ7r8xM7xQom+Ik0l5vxhs8quQ+5axjfMDc0qbnT3pmlwkuyEad8PUR9Nt5GeuKCAPC3IBXZyJqReNnXkOwlYeVuL2J0bSC+776MO58WQcmXvLxQIkNRj2Os7TA6Ese55t0QYxHVHubTtL1CQpnk1mYgEW4pe+kB10LeHwC2Xl+dpJztfy0mZjr0dnwgAuVRiA8ajNmLq8KIhwgT7hcImYZiJ0nj9TP7IVQLIMm0FPd9jSZNaT3Iufj9qLwzua8/85XKG8D9dW/x6feaKbdB8xfYxAEnNr3euvG7N5W7eE3mIrSQYZ+KYexZh0obN8p4d11SYAcXWEPE87oHsAq7zNAugpZb0w77gG2amvPSv5wWOIPxjM6g7uJ6asJQDPeO1+PeuZqGTl2lRzxxiu+7hUka/ZPp4GBUKek6YH169ZfDdYh2nOCZyco+f1zyaaIlTe86T4DYs+Bafeg7aIqcNUvgzKZCnCTL3GLsJfZHfK9geAPxETy3vIxyxZX9WxXvJGuRv2QOzFeRQUyaQtBwc3htv9c8OIelnWRPcdW7nc/j/j2pJi7xVDWwllhhaFvFOglhhZBdZLG3wX3HZYZOVznxk=
  app: vast-badlands-90141
